### ISSUE TITLE
Push subscription has unsubscribed or expired

### ISSUE THREAD

**Issue by failhunterby** [pushy-me/pushy-node-backend#1]
Time to time im getting error then trying to send notification

{"statusCode":410,"body":"push subscription has unsubscribed or expired.\n","name":"WebPushError","message":"Received unexpected response code"}
And i dont know how to investigate how things going. Any advice?

**Comment by pushy** [comment]
Hi @failhunterby,
Thanks for reaching out. We'd be glad to assist.

The error means that the visitor has unregistered the service worker for your website or disabled the notification permission from the browser settings. The visitor will need to return to your website, and you will need to call `Pushy.register()` again so that the service worker gets reinstalled. 

Registration will fail if the user previously declined the Web Push permission dialog, in which case notification preferences for your hostname must be cleared in the browser settings for the dialog to be displayed again:

**Chrome**: Enter `chrome://settings/content/notifications` in the address bar
**Firefox**: Enter `about:preferences#content` in the address bar ([detailed instructions](https://support.pushy.me/hc/en-us/articles/360043762272-Firefox-User-denied-permission-to-use-the-Push-API))
**iOS 16.4+**: Toggle "Allow Notifications" in the device settings for your PWA app, and restart the app
